@Echo Off
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class24.cvf" .\Class_24\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class25.cvf" .\Class_25\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class31.cvf" .\Class_31\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class37.cvf" .\Class_37\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class40.cvf" .\Class_40\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class45.cvf" .\Class_45\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class47.cvf" .\Class_47\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class50.cvf" .\Class_50\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class55.cvf" .\Class_55\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class56.cvf" .\Class_56\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class60.cvf" .\Class_60\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class66.cvf" .\Class_66\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class67.cvf" .\Class_67\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class86.cvf" .\Class_86\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class87.cvf" .\Class_87\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Class90.cvf" .\Class_90\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Deltic.cvf" .\Deltic\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class25n.cvf" .\Class_25\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class31n.cvf" .\Class_31\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class37n.cvf" .\Class_37\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class40n.cvf" .\Class_40\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class45n.cvf" .\Class_45\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class47n.cvf" .\Class_47\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class50n.cvf" .\Class_50\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class55n.cvf" .\Class_55\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class56n.cvf" .\Class_56\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class66n.cvf" .\Class_66\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class86n.cvf" .\Class_86\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Class90n.cvf" .\Class_90\Night\ /y
call xcopy "..\Common.Cab\Cab_Views_Right_Hand\Night\Delticn.cvf" .\Deltic\Night\ /y
